input {
    beats {
        port => 5044
    }
}

filter {
    mutate { add_field => { "Aynur" => "is here" } }
}

output {
     if [log][syslog][hostname] == "a-pc" {
        elasticsearch {
            hosts => ["http://els-hot:9200"]
            ssl_enabled => false
            index => "logs-syslog"
        }
    } else {
        elasticsearch {
            hosts => ["http://els-hot:9200"]
            ssl_enabled => false
            index => "logs-docker"
        }
    }
    stdout { codec => rubydebug }
}

