---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-aynur
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/learn/kuber/pv-aynur
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aynur
  namespace: netology-learn
spec:
  volumeName: pv-aynur
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
  namespace: netology-learn
spec:
  replicas: 1
  selector:
    matchLabels:
      aynur: here
  template:
    metadata:
      labels:
        aynur: here
    spec:
      containers:
      - name: writer-ctr
        image: busybox:latest
        command:
            - sh
            - -c
            - |
              while true; do
                echo "$(date): привет от Айнур!" >> /out/squirrel
                sleep 5
              done
        volumeMounts:
        - name: vol-aynur
          mountPath: /out
      - name: reader-ctr
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args: ["tail -f in/squirrel"]
        volumeMounts:
        - name: vol-aynur
          mountPath: /in
      volumes:
      - name: vol-aynur
        persistentVolumeClaim:
          claimName: pvc-aynur