{
 "title": "cpu, mem",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "WLAN received bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_network_receive_bytes_total{device=\"wlp0s20f3\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "node_network_transmit_bytes_total{device=\"wlp0s20f3\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Speed in Mbps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{device!~\"lo|veth.*|docker.*|br.*\"}[5m]) * 8\n",
       "legendFormat": "download"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{device!~\"lo|veth.*|docker.*|br.*\"}[5m]) * 8\n",
       "legendFormat": "upload"
      }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "mem total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"host.docker.internal:9100\"}",
       "legendFormat": "TOTAL "
      }
     ]
    },
    {
     "title": "Free memory",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Mem Pie",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"host.docker.internal:9100\"}",
       "legendFormat": "free"
      },
      {
       "expr": "node_memory_MemAvailable_bytes - node_memory_MemFree_bytes",
       "legendFormat": "Cached / Buffers"
      }
     ]
    },
    {
     "title": "Total and free memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "node_memory_MemTotal_bytes", "legendFormat": "total" },
      { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" }
     ]
    }
   ]
  },
  {
   "title": "cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) / sum(rate(node_cpu_seconds_total[5m])))*100",
       "legendFormat": "Current CPU load"
      }
     ]
    },
    {
     "title": "Свободное место в системе",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Тактовая частота каждого ядра процессора ",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 14, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "node_cpu_scaling_frequency_hertz{cpu=\"15\"}",
       "legendFormat": "15"
      },
      {
       "expr": "node_cpu_scaling_frequency_hertz{cpu=\"0\"}",
       "legendFormat": "0"
      },
      {
       "expr": "node_cpu_scaling_frequency_hertz{cpu=\"1\"}",
       "legendFormat": "1"
      },
      {
       "expr": "node_cpu_scaling_frequency_hertz{cpu=\"2\"}",
       "legendFormat": "2"
      },
      {
       "expr": "node_cpu_scaling_frequency_hertz{cpu=\"3\"}",
       "legendFormat": "3"
      },
      {
       "expr": "node_cpu_scaling_frequency_hertz{cpu=\"4\"}",
       "legendFormat": "4"
      },
      {
       "expr": "node_cpu_scaling_frequency_hertz{cpu=\"10\"}",
       "legendFormat": "10"
      },
      {
       "expr": "node_cpu_scaling_frequency_hertz{cpu=\"5\"}",
       "legendFormat": "5"
      }
     ]
    },
    {
     "title": "CPU load average for 1, 5 and 15 minutes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "node_load1", "legendFormat": "{{label_name}}" },
      { "expr": "node_load5", "legendFormat": "{{label_name}}" },
      { "expr": "node_load15", "legendFormat": "{{label_name}}" }
     ]
    }
   ]
  },
  {
   "title": "disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "filesystem_free_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "(1 - (node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})) * 100",
       "legendFormat": "main disk free in percent"
      }
     ]
    },
    {
     "title": "Free bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "node_filesystem_free_bytes", "legendFormat": "{{device}}" }
     ]
    }
   ]
  }
 ]
}