[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  hostname = "${HOST_NAME}"
  omit_hostname = false
  debug = false
  quiet = false

# Настройка отправки данных в InfluxDB v2
[[outputs.influxdb_v2]]
  urls = ["${INFLUX_HOST}"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

# Сбор базовых метрик системы
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.processes]]

[[inputs.mem]] # Оперативная память (RAM)
[[inputs.cgroup]]

[[inputs.disk]] # Диски и Inodes
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.system]] # Load Average (LA)

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_state_include = ["running", "healthy"]
  timeout = "5s"
  perdevice_include = ["cpu", "blkio", "network"]
  total_include = ["cpu", "blkio", "network"]