apiVersion: v1
kind: Service
metadata:
  name: np-service
  namespace: netology-learn
spec:
  type: NodePort
  selector:
    app: aynur
  ports:
    - name: nginx-nodeport
      protocol: TCP
      port: 80
      nodePort: 30080
