apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true

  - name: PostgreSQL_Events
    type: postgres
    url: postgres:5432
    database: auth
    user: aynur
    secureJsonData:
      password: qwertyAynur
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifecycle: 14400
