apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-multitool
      version: v1
  template:
    metadata:
      labels:
        app: nginx-multitool
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-page
          mountPath: /usr/share/nginx/html
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8080
        env:
          - name: HTTP_PORT
            value: "8080"
      volumes:
      - name: web-page
        configMap:
          name: nginx-v1-config
          