autoscaling:
  enabled: false
replicaCount: 1

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"

cons:
  - name: nginx
    image: nginx:latest
    containerPort: 80
    volumeMounts:
      - name: index-vol
        mountPath: /usr/share/nginx/html
    
  - name: multitool
    image: wbitt/network-multitool:latest
    containerPort: 8080
    env:
      - name: HTTP_PORT
        value: "8080"
      - name: HTTPS_PORT
        value: "10443"

volumes:
  - name: index-vol
    configMap:
      items:
        - key: index.html
          path: index.html

nodeSelector: {
  aynur: configmap
}
