clickhouse:
  hosts:
    clickhouse:
      ansible_host: 51.250.42.180
      ansible_user: aynur
      ansible_become: true
lighthouse:
  hosts:
    lighthouse:
      ansible_host: 81.26.190.192
      ansible_user: aynur
      ansible_become: true
vector:
  hosts:
    vector:
      ansible_host: 158.160.149.135
      ansible_user: aynur
      ansible_become: true
